### ISSUE TITLE
Is there any effort underway to consolidate multiple github repositories

### ISSUE THREAD

**Issue by mayureshw** [efabless/skywater-pdk-libs-sky130_fd_pr#25]
I spent quite a lot of time with errors faced when using google/skywater-pdk-libs-sky130_fd_pr repo before seeing a github post that pointed me to this repo.

I am sure many people might be facing this.

From the commit logs it appears that this repo is the one maintained.

Is there any effort possible from all collaborating companies to consolidate the repos to remove this confusion by not having multiple repositories with same names.

**Comment by RTimothyEdwards** [comment]
@mayureshw :  The issue is that Google is no longer maintaining the upstream repository, and so there is nobody there who will update the repository;  otherwise I would have issued pull requests to the Google repository to be merged there rather than maintaining my own fork of the PDK.  There has been an effort by Google to move maintenance of the repository to another entity.  I am fine with that effort, and would like to see the PDK and documentation in a single location, although I haven't heard of any progress on that front recently.

**Comment by RTimothyEdwards** [comment]
To be clear, it is not a "repository of the same name".  It is a fork of the Google repository on which I have continued with bug fixes and enhancements, most of which are still sitting as pull requests on the upstream repository and never merged.

**Comment by mayureshw** [comment]
Thanks for the clarification.
